In [1]:
import pandas as pd
import numpy as np
from io import StringIO 
import pyranges as pr

In [3]:
RAV_pred = pd.read_csv("soy_RAV_201bp_targets_DEG5999_0615_thres08_windowloc10_vn2.csv",header=0)
print(RAV_pred  )

           n                                   tgenes  indexarray
0          0      Glyma.01G004200::Gm01:427437-429437        1750
1          1      Glyma.01G004200::Gm01:427437-429437        1760
2          2      Glyma.01G004200::Gm01:427437-429437        1770
3          3      Glyma.01G004200::Gm01:427437-429437        1780
4          4      Glyma.01G004200::Gm01:427437-429437        1790
...      ...                                      ...         ...
65860  65860  Glyma.U003033::scaffold_138:22772-24772        1320
65861  65861  Glyma.U003033::scaffold_138:22772-24772        1330
65862  65862  Glyma.U003033::scaffold_138:22772-24772        1340
65863  65863  Glyma.U003033::scaffold_138:22772-24772        1350
65864  65864  Glyma.U003033::scaffold_138:22772-24772        1360

[65865 rows x 3 columns]

In [4]:
df_RAV_pred =RAV_pred .drop(['n'],axis=1)
df_RAV_pred

                                        tgenes  indexarray
0          Glyma.01G004200::Gm01:427437-429437        1750
1          Glyma.01G004200::Gm01:427437-429437        1760
2          Glyma.01G004200::Gm01:427437-429437        1770
3          Glyma.01G004200::Gm01:427437-429437        1780
4          Glyma.01G004200::Gm01:427437-429437        1790
...                                        ...         ...
65860  Glyma.U003033::scaffold_138:22772-24772        1320
65861  Glyma.U003033::scaffold_138:22772-24772        1330
65862  Glyma.U003033::scaffold_138:22772-24772        1340
65863  Glyma.U003033::scaffold_138:22772-24772        1350
65864  Glyma.U003033::scaffold_138:22772-24772        1360

[65865 rows x 2 columns]

In [5]:
promtoer_split = pd.DataFrame(df_RAV_pred .tgenes.str.split('::',2).tolist(),columns=['gene','location1'])

promtoer_split

                  gene                 location1
0      Glyma.01G004200        Gm01:427437-429437
1      Glyma.01G004200        Gm01:427437-429437
2      Glyma.01G004200        Gm01:427437-429437
3      Glyma.01G004200        Gm01:427437-429437
4      Glyma.01G004200        Gm01:427437-429437
...                ...                       ...
65860    Glyma.U003033  scaffold_138:22772-24772
65861    Glyma.U003033  scaffold_138:22772-24772
65862    Glyma.U003033  scaffold_138:22772-24772
65863    Glyma.U003033  scaffold_138:22772-24772
65864    Glyma.U003033  scaffold_138:22772-24772

[65865 rows x 2 columns]

In [6]:
pr_loc_split = pd.DataFrame(promtoer_split.location1.str.split(':',2).tolist(),columns=['chrom','location'])
pr_loc_split

              chrom       location
0              Gm01  427437-429437
1              Gm01  427437-429437
2              Gm01  427437-429437
3              Gm01  427437-429437
4              Gm01  427437-429437
...             ...            ...
65860  scaffold_138    22772-24772
65861  scaffold_138    22772-24772
65862  scaffold_138    22772-24772
65863  scaffold_138    22772-24772
65864  scaffold_138    22772-24772

[65865 rows x 2 columns]

In [7]:
prom_cod = pd.DataFrame(pr_loc_split.location.str.split('-',2).tolist(),columns=['start','end'])
prom_cod

        start     end
0      427437  429437
1      427437  429437
2      427437  429437
3      427437  429437
4      427437  429437
...       ...     ...
65860   22772   24772
65861   22772   24772
65862   22772   24772
65863   22772   24772
65864   22772   24772

[65865 rows x 2 columns]

In [8]:
promoter_wnd=pd.concat([df_RAV_pred ,promtoer_split,pr_loc_split,prom_cod],axis=1)
 
promoter_wnd

,tgenes,indexarray,gene,location1,chrom,location,start,end
0,Glyma.01G004200::Gm01:427437-429437,1750,Glyma.01G004200,Gm01:427437-429437,Gm01,427437-429437,427437,429437
1,Glyma.01G004200::Gm01:427437-429437,1760,Glyma.01G004200,Gm01:427437-429437,Gm01,427437-429437,427437,429437
2,Glyma.01G004200::Gm01:427437-429437,1770,Glyma.01G004200,Gm01:427437-429437,Gm01,427437-429437,427437,429437
3,Glyma.01G004200::Gm01:427437-429437,1780,Glyma.01G004200,Gm01:427437-429437,Gm01,427437-429437,427437,429437
4,Glyma.01G004200::Gm01:427437-429437,1790,Glyma.01G004200,Gm01:427437-429437,Gm01,427437-429437,427437,429437
...,...,...,...,...,...,...,...,...
65860,Glyma.U003033::scaffold_138:22772-24772,1320,Glyma.U003033,scaffold_138:22772-24772,scaffold_138,22772-24772,22772,24772
65861,Glyma.U003033::scaffold_138:22772-24772,1330,Glyma.U003033,scaffold_138:22772-24772,scaffold_138,22772-24772,22772,24772
65862,Glyma.U003033::scaffold_138:22772-24772,1340,Glyma.U003033,scaffold_138:22772-24772,scaffold_138,22772-24772,22772,24772
65863,Glyma.U003033::scaffold_138:22772-24772,1350,Glyma.U003033,scaffold_138:22772-24772,scaffold_138,22772-24772,22772,24772
65864,Glyma.U003033::scaffold_138:22772-24772,1360,Glyma.U003033,scaffold_138:22772-24772,scaffold_138,22772-24772,22772,24772

In [9]:
df_promoter_wnd=promoter_wnd.drop(['tgenes','location1','location'], axis=1)

#convert string data type to int
df_promoter_wnd['start']=df_promoter_wnd['start'].astype(int)
df_promoter_wnd['end']=df_promoter_wnd['end'].astype(int)
print(df_promoter_wnd)

       indexarray             gene         chrom   start     end
0            1750  Glyma.01G004200          Gm01  427437  429437
1            1760  Glyma.01G004200          Gm01  427437  429437
2            1770  Glyma.01G004200          Gm01  427437  429437
3            1780  Glyma.01G004200          Gm01  427437  429437
4            1790  Glyma.01G004200          Gm01  427437  429437
...           ...              ...           ...     ...     ...
65860        1320    Glyma.U003033  scaffold_138   22772   24772
65861        1330    Glyma.U003033  scaffold_138   22772   24772
65862        1340    Glyma.U003033  scaffold_138   22772   24772
65863        1350    Glyma.U003033  scaffold_138   22772   24772
65864        1360    Glyma.U003033  scaffold_138   22772   24772

[65865 rows x 5 columns]

In [10]:
df_promoter_wnd["windowstart"]=df_promoter_wnd["start"]+df_promoter_wnd["indexarray"]
df_promoter_wnd["windowend"]=df_promoter_wnd["windowstart"]+201
df_promoter_wnd

,indexarray,gene,chrom,start,end,windowstart,windowend
0,1750,Glyma.01G004200,Gm01,427437,429437,429187,429388
1,1760,Glyma.01G004200,Gm01,427437,429437,429197,429398
2,1770,Glyma.01G004200,Gm01,427437,429437,429207,429408
3,1780,Glyma.01G004200,Gm01,427437,429437,429217,429418
4,1790,Glyma.01G004200,Gm01,427437,429437,429227,429428
...,...,...,...,...,...,...,...
65860,1320,Glyma.U003033,scaffold_138,22772,24772,24092,24293
65861,1330,Glyma.U003033,scaffold_138,22772,24772,24102,24303
65862,1340,Glyma.U003033,scaffold_138,22772,24772,24112,24313
65863,1350,Glyma.U003033,scaffold_138,22772,24772,24122,24323
65864,1360,Glyma.U003033,scaffold_138,22772,24772,24132,24333

In [11]:
df_promoter_cod=df_promoter_wnd.drop(['indexarray','start','end'], axis=1)


df_promoter_cod_rearg=df_promoter_cod[["chrom", "windowstart", "windowend","gene"]]
df_promoter_cod_rearg

              chrom  windowstart  windowend             gene
0              Gm01       429187     429388  Glyma.01G004200
1              Gm01       429197     429398  Glyma.01G004200
2              Gm01       429207     429408  Glyma.01G004200
3              Gm01       429217     429418  Glyma.01G004200
4              Gm01       429227     429428  Glyma.01G004200
...             ...          ...        ...              ...
65860  scaffold_138        24092      24293    Glyma.U003033
65861  scaffold_138        24102      24303    Glyma.U003033
65862  scaffold_138        24112      24313    Glyma.U003033
65863  scaffold_138        24122      24323    Glyma.U003033
65864  scaffold_138        24132      24333    Glyma.U003033

[65865 rows x 4 columns]

In [12]:
import pybedtools

fbed = pybedtools.BedTool.from_dataframe(df_promoter_cod_rearg)\
              .saveas('RAV_10W_DEG5999_target_windows_0.8thresh.bed')